package com.xtrapay.commons

object EmvTag {
    const val ACQUIRER_IDENTIFIER_9F01 = 0X9F01
    const val TERMINAL_COUNTRY_CODE_9F1A = 0x9F1A
    const val TRANSACTION_CURRENCY_CODE_5F2A = 0x5F2A
    const val TRANSACTION_CURRENCY_EXPONENT_5F36 = 0x5F36
    const val MERCHANT_NAME_AND_LOCATION_9F4E = 0x9F4E
    const val MERCHANT_CATEGORY_CODE_9F15 = 0x9F15
    const val MERCHANT_IDENTIFIER_9F16 = 0x9F16
    const val TERMINAL_IDENTIFIER_9F1C = 0x9F1C
    const val TERMINAL_CAPABILITIES_9F33 = 0x9F33
    const val TERMINAL_TYPE_9F35 = 0x9F35
    const val TERMINAL_ADDITIONAL_CAPABILITIES_9F40 = 0x9F40


    const val APPLICATION_CRYPTOGRAM_9F26 = 0x9F26
    const val CRYPTOGRAM_INFO_DATA_9F27 = 0x9F27
    const val ISSUER_APPLICATION_DATA_9F10 = 0x9F10
    const val UNPREDICTABLE_NUMBER_9F37 = 0x9F37
    const val APPLICATION_TRANSACTION_COUNTER_9F36 = 0x9F36
    const val TERMINAL_VERIFICATION_RESULT_95 = 0x95
    const val TRANSACTION_DATE_9A = 0x9A
    const val TRANSACTION_TYPE_9C = 0x9C
    const val PAN_SEQUENCE_NUMBER_5F34 = 0x5F34
    const val APPLICATION_INTERCHANGE_PROFILE_82 = 0x82

    const val AMOUNT_AUTHORIZED_9F02 = 0x9F02
    const val AMOUNT_OTHER_9F03 = 0x9F03

    const val DEDICATED_FILE_NAME_84 = 0x84
    const val APPLICATION_VERSION_NUMBER_CARD_9F08 = 0x9F08
    const val CARDHOLDER_VERIFICATION_ACTION_9F34 = 0x9F34

    const val INTERFACE_DEVICE_SERIAL_NUMBER_9F1E = 0x9F1E
    const val CONSECUTIVE_TRANSACTION_COUNTER_9F53 = 0x9F53
    const val APPLICATION_VERSION_NUMBER_TERMINAL_9F09 = 0x9F09
    const val TRANSACTION_SEQUENCE_COUNTER_9F41 = 0x9F41

    const val ENCRYPTED_PIN_BLOCK_9F62 = 0x9F62
    const val ENCRYPTED_PIN_BLOCK_DF01 = 0xDF01
    const val CARDHOLDER_NAME_5F20 = 0x5F20
    const val TRACK_2_EQUIVALENT_DATA = 0x57
    const val CVM_LIST = 0x8E

    const val TRANSACTION_REFERENCE_CURRENCY_CODE_9F3C = 0x9F3C
    const val SERVICE_CODE_5F30 = 0x5F30
    const val TVR_95 = 0x95
    const val TSI_9B = 0x9B
    const val TC_98 = 0x98

    const val APPLICATION_LABEL = 0x50

    const val ISSUER_AUTHENTICATION_DATA_91 = 0x91
    const val ISSUER_SCRIPT_71 = 0x71
    const val ISSUER_SCRIPT_72 = 0x72
    const val FORM_FACTOR_INDICATOR_9F6E = 0x9F6E

    const val POS_ENTRY_MODE_9F39 = 0x9F39


    val nibssRequestTags = intArrayOf(
        APPLICATION_CRYPTOGRAM_9F26,
        CRYPTOGRAM_INFO_DATA_9F27,
        ISSUER_APPLICATION_DATA_9F10,
        UNPREDICTABLE_NUMBER_9F37,
        APPLICATION_TRANSACTION_COUNTER_9F36,
        TERMINAL_VERIFICATION_RESULT_95,
        TRANSACTION_DATE_9A,
        TRANSACTION_TYPE_9C,
        AMOUNT_AUTHORIZED_9F02,
        TRANSACTION_CURRENCY_CODE_5F2A,
        APPLICATION_INTERCHANGE_PROFILE_82,
        TERMINAL_COUNTRY_CODE_9F1A,
        CARDHOLDER_VERIFICATION_ACTION_9F34,
        TERMINAL_CAPABILITIES_9F33,
        TERMINAL_TYPE_9F35,
        INTERFACE_DEVICE_SERIAL_NUMBER_9F1E,
        DEDICATED_FILE_NAME_84,
        APPLICATION_VERSION_NUMBER_TERMINAL_9F09,
        AMOUNT_OTHER_9F03,
        PAN_SEQUENCE_NUMBER_5F34,
        CVM_LIST
    )

    val nibssResponseTags = intArrayOf(
        ISSUER_AUTHENTICATION_DATA_91,
        ISSUER_SCRIPT_71,
        ISSUER_SCRIPT_72,
        FORM_FACTOR_INDICATOR_9F6E
    )
}